# Official ffmpeg compilation guide in Ansible style
# https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

- assert:
    that:
      - "'{{ ffmpeg_role_action }}' in [ 'install', 'uninstall', 'update']"

- include: install.yml
