---

- name: remove ffmpeg dirs
  file: name={{ item }} state=absent
  with_items:
    - "{{ ffmpeg_build_dir }}"
    - "{{ ffmpeg_source_dir }}"
    - "{{ ffmpeg_bin_dir }}/ffmpeg"
    - "{{ ffmpeg_bin_dir }}/ffprobe"
    - "{{ ffmpeg_bin_dir }}/ffserver"
    - "{{ ffmpeg_bin_dir }}/vsyasm"
    - "{{ ffmpeg_bin_dir }}/x264"
    - "{{ ffmpeg_bin_dir }}/yasm"
    - "{{ ffmpeg_bin_dir }}/ytasm"
  tags:
    - remove_dirs

- name: remove deps
    shell: apt-get autoremove
    with_items: ffmpeg_deps
    when: ffmpeg_remove_deps

- name: remove manpath map
  shell: sed -i '/ffmpeg_build/c\' /etc/manpath.config